
insert into medicine_items(name, alias, category, effects, actions_and_indications,
	details, common_prescriptions, common_partners, similar_medicines, dosage_reference,
	contraindications, remarks)
values(/* name: */ '洋葱',
	/* alias: */ '',
	/* category: */ 0,
	/* effects: */ '',
	/* actions_and_indications: */ '',
	/* details: */ '',
	/* common_prescriptions: */ '',
	/* common_partners: */ '',
	/* similar_medicines: */ '',
	/* dosage_reference: */ '一般用量为X～X克，重症时可用X～X克',
	/* contraindications: */ '',
	/* remarks: */ '' );

insert into medicine_items(name, alias, category, effects, actions_and_indications,
	details, common_prescriptions, common_partners, similar_medicines, dosage_reference,
	contraindications, remarks)
values(/* name: */ '芹菜',
	/* alias: */ '',
	/* category: */ 0,
	/* effects: */ '',
	/* actions_and_indications: */ '',
	/* details: */ '',
	/* common_prescriptions: */ '',
	/* common_partners: */ '',
	/* similar_medicines: */ '',
	/* dosage_reference: */ '一般用量为X～X克，重症时可用X～X克',
	/* contraindications: */ '',
	/* remarks: */ '' );

insert into medicine_items(name, alias, category, effects, actions_and_indications,
	details, common_prescriptions, common_partners, similar_medicines, dosage_reference,
	contraindications, remarks)
values(/* name: */ '菠菜',
	/* alias: */ '',
	/* category: */ 0,
	/* effects: */ '',
	/* actions_and_indications: */ '',
	/* details: */ '',
	/* common_prescriptions: */ '',
	/* common_partners: */ '',
	/* similar_medicines: */ '',
	/* dosage_reference: */ '一般用量为X～X克，重症时可用X～X克',
	/* contraindications: */ '',
	/* remarks: */ '' );

insert into medicine_items(name, alias, category, effects, actions_and_indications,
	details, common_prescriptions, common_partners, similar_medicines, dosage_reference,
	contraindications, remarks)
values(/* name: */ '蕹菜',
	/* alias: */ '',
	/* category: */ 0,
	/* effects: */ '',
	/* actions_and_indications: */ '',
	/* details: */ '',
	/* common_prescriptions: */ '',
	/* common_partners: */ '',
	/* similar_medicines: */ '',
	/* dosage_reference: */ '一般用量为X～X克，重症时可用X～X克',
	/* contraindications: */ '',
	/* remarks: */ '' );

insert into medicine_items(name, alias, category, effects, actions_and_indications,
	details, common_prescriptions, common_partners, similar_medicines, dosage_reference,
	contraindications, remarks)
values(/* name: */ '白菜',
	/* alias: */ '',
	/* category: */ 0,
	/* effects: */ '',
	/* actions_and_indications: */ '',
	/* details: */ '',
	/* common_prescriptions: */ '',
	/* common_partners: */ '',
	/* similar_medicines: */ '',
	/* dosage_reference: */ '一般用量为X～X克，重症时可用X～X克',
	/* contraindications: */ '',
	/* remarks: */ '' );

insert into medicine_items(name, alias, category, effects, actions_and_indications,
	details, common_prescriptions, common_partners, similar_medicines, dosage_reference,
	contraindications, remarks)
values(/* name: */ '芥菜',
	/* alias: */ '',
	/* category: */ 0,
	/* effects: */ '',
	/* actions_and_indications: */ '',
	/* details: */ '',
	/* common_prescriptions: */ '',
	/* common_partners: */ '',
	/* similar_medicines: */ '',
	/* dosage_reference: */ '一般用量为X～X克，重症时可用X～X克',
	/* contraindications: */ '',
	/* remarks: */ '' );

insert into medicine_items(name, alias, category, effects, actions_and_indications,
	details, common_prescriptions, common_partners, similar_medicines, dosage_reference,
	contraindications, remarks)
values(/* name: */ '油菜',
	/* alias: */ '',
	/* category: */ 0,
	/* effects: */ '',
	/* actions_and_indications: */ '',
	/* details: */ '',
	/* common_prescriptions: */ '',
	/* common_partners: */ '',
	/* similar_medicines: */ '',
	/* dosage_reference: */ '一般用量为X～X克，重症时可用X～X克',
	/* contraindications: */ '',
	/* remarks: */ '' );

insert into medicine_items(name, alias, category, effects, actions_and_indications,
	details, common_prescriptions, common_partners, similar_medicines, dosage_reference,
	contraindications, remarks)
values(/* name: */ '包菜',
	/* alias: */ '',
	/* category: */ 0,
	/* effects: */ '',
	/* actions_and_indications: */ '',
	/* details: */ '',
	/* common_prescriptions: */ '',
	/* common_partners: */ '',
	/* similar_medicines: */ '',
	/* dosage_reference: */ '一般用量为X～X克，重症时可用X～X克',
	/* contraindications: */ '',
	/* remarks: */ '' );

insert into medicine_items(name, alias, category, effects, actions_and_indications,
	details, common_prescriptions, common_partners, similar_medicines, dosage_reference,
	contraindications, remarks)
values(/* name: */ '枸杞菜',
	/* alias: */ '',
	/* category: */ 0,
	/* effects: */ '',
	/* actions_and_indications: */ '',
	/* details: */ '',
	/* common_prescriptions: */ '',
	/* common_partners: */ '',
	/* similar_medicines: */ '',
	/* dosage_reference: */ '一般用量为X～X克，重症时可用X～X克',
	/* contraindications: */ '',
	/* remarks: */ '' );

insert into medicine_items(name, alias, category, effects, actions_and_indications,
	details, common_prescriptions, common_partners, similar_medicines, dosage_reference,
	contraindications, remarks)
values(/* name: */ '西洋菜',
	/* alias: */ '',
	/* category: */ 0,
	/* effects: */ '',
	/* actions_and_indications: */ '',
	/* details: */ '',
	/* common_prescriptions: */ '',
	/* common_partners: */ '',
	/* similar_medicines: */ '',
	/* dosage_reference: */ '一般用量为X～X克，重症时可用X～X克',
	/* contraindications: */ '',
	/* remarks: */ '' );

insert into medicine_items(name, alias, category, effects, actions_and_indications,
	details, common_prescriptions, common_partners, similar_medicines, dosage_reference,
	contraindications, remarks)
values(/* name: */ '大头菜',
	/* alias: */ '',
	/* category: */ 0,
	/* effects: */ '',
	/* actions_and_indications: */ '',
	/* details: */ '',
	/* common_prescriptions: */ '',
	/* common_partners: */ '',
	/* similar_medicines: */ '',
	/* dosage_reference: */ '一般用量为X～X克，重症时可用X～X克',
	/* contraindications: */ '',
	/* remarks: */ '' );

insert into medicine_items(name, alias, category, effects, actions_and_indications,
	details, common_prescriptions, common_partners, similar_medicines, dosage_reference,
	contraindications, remarks)
values(/* name: */ '莙荙菜',
	/* alias: */ '',
	/* category: */ 0,
	/* effects: */ '',
	/* actions_and_indications: */ '',
	/* details: */ '',
	/* common_prescriptions: */ '',
	/* common_partners: */ '',
	/* similar_medicines: */ '',
	/* dosage_reference: */ '一般用量为X～X克，重症时可用X～X克',
	/* contraindications: */ '',
	/* remarks: */ '' );

insert into medicine_items(name, alias, category, effects, actions_and_indications,
	details, common_prescriptions, common_partners, similar_medicines, dosage_reference,
	contraindications, remarks)
values(/* name: */ '香花菜',
	/* alias: */ '',
	/* category: */ 0,
	/* effects: */ '',
	/* actions_and_indications: */ '',
	/* details: */ '',
	/* common_prescriptions: */ '',
	/* common_partners: */ '',
	/* similar_medicines: */ '',
	/* dosage_reference: */ '一般用量为X～X克，重症时可用X～X克',
	/* contraindications: */ '',
	/* remarks: */ '' );

insert into medicine_items(name, alias, category, effects, actions_and_indications,
	details, common_prescriptions, common_partners, similar_medicines, dosage_reference,
	contraindications, remarks)
values(/* name: */ '红苋菜',
	/* alias: */ '',
	/* category: */ 0,
	/* effects: */ '',
	/* actions_and_indications: */ '',
	/* details: */ '',
	/* common_prescriptions: */ '',
	/* common_partners: */ '',
	/* similar_medicines: */ '',
	/* dosage_reference: */ '一般用量为X～X克，重症时可用X～X克',
	/* contraindications: */ '',
	/* remarks: */ '' );

insert into medicine_items(name, alias, category, effects, actions_and_indications,
	details, common_prescriptions, common_partners, similar_medicines, dosage_reference,
	contraindications, remarks)
values(/* name: */ '冬苋菜',
	/* alias: */ '',
	/* category: */ 0,
	/* effects: */ '',
	/* actions_and_indications: */ '',
	/* details: */ '',
	/* common_prescriptions: */ '',
	/* common_partners: */ '',
	/* similar_medicines: */ '',
	/* dosage_reference: */ '一般用量为X～X克，重症时可用X～X克',
	/* contraindications: */ '',
	/* remarks: */ '' );

